[2021-04-05 07:20:02,523] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: fec_lead_importer.main 2021-04-05T07:10:00+00:00 [queued]>
[2021-04-05 07:20:02,607] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: fec_lead_importer.main 2021-04-05T07:10:00+00:00 [queued]>
[2021-04-05 07:20:02,607] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-04-05 07:20:02,607] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-04-05 07:20:02,607] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-04-05 07:20:02,651] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): main> on 2021-04-05T07:10:00+00:00
[2021-04-05 07:20:02,681] {standard_task_runner.py:51} INFO - Started process 353682 to run task
[2021-04-05 07:20:02,687] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'fec_lead_importer', 'main', '2021-04-05T07:10:00+00:00', '--job-id', '338', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/airflow_poc.py', '--cfg-path', '/tmp/tmpqiefiq8u']
[2021-04-05 07:20:02,717] {standard_task_runner.py:76} INFO - Job 338: Subtask main
[2021-04-05 07:20:03,112] {logging_mixin.py:103} INFO - Running <TaskInstance: fec_lead_importer.main 2021-04-05T07:10:00+00:00 [running]> on host airflowvm
[2021-04-05 07:20:03,280] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=fec_lead_importer
AIRFLOW_CTX_TASK_ID=main
AIRFLOW_CTX_EXECUTION_DATE=2021-04-05T07:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-05T07:10:00+00:00
[2021-04-05 07:20:03,281] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-04-05 07:20:03,289] {bash.py:158} INFO - Running command: $HOME/workspace/cron-jobs/scripts/standard/leads_importer/fec_importer.sh --client 'fec' --upsert 'true'
[2021-04-05 07:20:03,304] {bash.py:169} INFO - Output:
[2021-04-05 07:20:03,315] {bash.py:173} INFO - bash: /home/airflow/workspace/cron-jobs/scripts/standard/leads_importer/fec_importer.sh: No such file or directory
[2021-04-05 07:20:03,322] {bash.py:177} INFO - Command exited with return code 127
[2021-04-05 07:20:03,350] {taskinstance.py:1396} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-04-05 07:20:03,351] {taskinstance.py:1433} INFO - Marking task as FAILED. dag_id=fec_lead_importer, task_id=main, execution_date=20210405T071000, start_date=20210405T072002, end_date=20210405T072003
[2021-04-05 07:20:03,435] {local_task_job.py:118} INFO - Task exited with return code 1
