[2021-03-10 09:22:47,632] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: parallel_dag.bash1 2021-03-09T00:00:00+00:00 [queued]>
[2021-03-10 09:22:47,637] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: parallel_dag.bash1 2021-03-09T00:00:00+00:00 [queued]>
[2021-03-10 09:22:47,637] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-03-10 09:22:47,637] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-03-10 09:22:47,637] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-03-10 09:22:47,648] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): bash1> on 2021-03-09T00:00:00+00:00
[2021-03-10 09:22:47,649] {standard_task_runner.py:51} INFO - Started process 45685 to run task
[2021-03-10 09:22:47,654] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'bash1', '2021-03-09T00:00:00+00:00', '--job-id', '298', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpreutpvcy']
[2021-03-10 09:22:47,654] {standard_task_runner.py:76} INFO - Job 298: Subtask bash1
[2021-03-10 09:22:47,810] {logging_mixin.py:103} INFO - Running <TaskInstance: parallel_dag.bash1 2021-03-09T00:00:00+00:00 [running]> on host airflowvm
[2021-03-10 09:22:47,981] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=bash1
AIRFLOW_CTX_EXECUTION_DATE=2021-03-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-09T00:00:00+00:00
[2021-03-10 09:22:47,981] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-03-10 09:22:47,981] {bash.py:158} INFO - Running command: sleep(3)
[2021-03-10 09:22:47,984] {bash.py:169} INFO - Output:
[2021-03-10 09:22:47,986] {bash.py:173} INFO - bash: -c: line 0: syntax error near unexpected token `3'
[2021-03-10 09:22:47,986] {bash.py:173} INFO - bash: -c: line 0: `sleep(3)'
[2021-03-10 09:22:47,986] {bash.py:177} INFO - Command exited with return code 1
[2021-03-10 09:22:47,991] {taskinstance.py:1396} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-03-10 09:22:47,992] {taskinstance.py:1433} INFO - Marking task as FAILED. dag_id=parallel_dag, task_id=bash1, execution_date=20210309T000000, start_date=20210310T092247, end_date=20210310T092247
[2021-03-10 09:22:48,032] {local_task_job.py:118} INFO - Task exited with return code 1
[2021-03-10 09:48:33,062] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: parallel_dag.bash1 2021-03-09T00:00:00+00:00 [queued]>
[2021-03-10 09:48:33,096] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: parallel_dag.bash1 2021-03-09T00:00:00+00:00 [queued]>
[2021-03-10 09:48:33,096] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-03-10 09:48:33,096] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-03-10 09:48:33,096] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-03-10 09:48:33,112] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): bash1> on 2021-03-09T00:00:00+00:00
[2021-03-10 09:48:33,113] {standard_task_runner.py:51} INFO - Started process 80937 to run task
[2021-03-10 09:48:33,130] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'bash1', '2021-03-09T00:00:00+00:00', '--job-id', '3', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp33qtsp9w']
[2021-03-10 09:48:33,130] {standard_task_runner.py:76} INFO - Job 3: Subtask bash1
[2021-03-10 09:48:33,390] {logging_mixin.py:103} INFO - Running <TaskInstance: parallel_dag.bash1 2021-03-09T00:00:00+00:00 [running]> on host airflowvm
[2021-03-10 09:48:33,589] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=bash1
AIRFLOW_CTX_EXECUTION_DATE=2021-03-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-09T00:00:00+00:00
[2021-03-10 09:48:33,590] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-03-10 09:48:33,590] {bash.py:158} INFO - Running command: sleep 3
[2021-03-10 09:48:33,604] {bash.py:169} INFO - Output:
[2021-03-10 09:48:36,625] {bash.py:177} INFO - Command exited with return code 0
[2021-03-10 09:48:36,687] {taskinstance.py:1135} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=bash1, execution_date=20210309T000000, start_date=20210310T094833, end_date=20210310T094836
[2021-03-10 09:48:36,760] {taskinstance.py:1195} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2021-03-10 09:48:36,786] {local_task_job.py:118} INFO - Task exited with return code 0
