[2021-04-05 05:50:18,898] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: baxa_lead_importer.main 2021-04-05T05:40:00+00:00 [queued]>
[2021-04-05 05:50:18,959] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: baxa_lead_importer.main 2021-04-05T05:40:00+00:00 [queued]>
[2021-04-05 05:50:18,959] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-04-05 05:50:18,959] {taskinstance.py:1018} INFO - Starting attempt 2 of 2
[2021-04-05 05:50:18,959] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-04-05 05:50:19,003] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): main> on 2021-04-05T05:40:00+00:00
[2021-04-05 05:50:19,019] {standard_task_runner.py:51} INFO - Started process 110338 to run task
[2021-04-05 05:50:19,032] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'baxa_lead_importer', 'main', '2021-04-05T05:40:00+00:00', '--job-id', '312', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/baxa_lead_importer.py', '--cfg-path', '/tmp/tmpzpw8h2t0']
[2021-04-05 05:50:19,033] {standard_task_runner.py:76} INFO - Job 312: Subtask main
[2021-04-05 05:50:19,263] {logging_mixin.py:103} INFO - Running <TaskInstance: baxa_lead_importer.main 2021-04-05T05:40:00+00:00 [running]> on host airflowvm
[2021-04-05 05:50:19,461] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=baxa_lead_importer
AIRFLOW_CTX_TASK_ID=main
AIRFLOW_CTX_EXECUTION_DATE=2021-04-05T05:40:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-05T05:40:00+00:00
[2021-04-05 05:50:19,462] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-04-05 05:50:19,462] {bash.py:158} INFO - Running command: sleep 20
[2021-04-05 05:50:19,494] {bash.py:169} INFO - Output:
[2021-04-05 05:50:29,471] {timeout.py:36} ERROR - Process timed out, PID: 110338
[2021-04-05 05:50:29,471] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2021-04-05 05:50:29,489] {taskinstance.py:1396} ERROR - Timeout, PID: 110338
Traceback (most recent call last):
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1295, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/operators/bash.py", line 171, in execute
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: Timeout, PID: 110338
[2021-04-05 05:50:29,490] {taskinstance.py:1433} INFO - Marking task as FAILED. dag_id=baxa_lead_importer, task_id=main, execution_date=20210405T054000, start_date=20210405T055018, end_date=20210405T055029
[2021-04-05 05:50:29,537] {local_task_job.py:118} INFO - Task exited with return code 1
