[2021-04-05 07:20:02,166] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: baxa_lead_importer.main 2021-04-05T07:10:00+00:00 [queued]>
[2021-04-05 07:20:02,219] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: baxa_lead_importer.main 2021-04-05T07:10:00+00:00 [queued]>
[2021-04-05 07:20:02,220] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-04-05 07:20:02,220] {taskinstance.py:1018} INFO - Starting attempt 1 of 2
[2021-04-05 07:20:02,220] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-04-05 07:20:02,263] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): main> on 2021-04-05T07:10:00+00:00
[2021-04-05 07:20:02,283] {standard_task_runner.py:51} INFO - Started process 353667 to run task
[2021-04-05 07:20:02,330] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'baxa_lead_importer', 'main', '2021-04-05T07:10:00+00:00', '--job-id', '337', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/baxa_lead_importer.py', '--cfg-path', '/tmp/tmphxc3l641']
[2021-04-05 07:20:02,331] {standard_task_runner.py:76} INFO - Job 337: Subtask main
[2021-04-05 07:20:02,637] {logging_mixin.py:103} INFO - Running <TaskInstance: baxa_lead_importer.main 2021-04-05T07:10:00+00:00 [running]> on host airflowvm
[2021-04-05 07:20:03,059] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=baxa_lead_importer
AIRFLOW_CTX_TASK_ID=main
AIRFLOW_CTX_EXECUTION_DATE=2021-04-05T07:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-05T07:10:00+00:00
[2021-04-05 07:20:03,060] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-04-05 07:20:03,060] {bash.py:158} INFO - Running command: sleep 20
[2021-04-05 07:20:03,102] {bash.py:169} INFO - Output:
[2021-04-05 07:20:13,060] {timeout.py:36} ERROR - Process timed out, PID: 353667
[2021-04-05 07:20:13,060] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2021-04-05 07:20:13,103] {taskinstance.py:1396} ERROR - Timeout, PID: 353667
Traceback (most recent call last):
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1295, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/operators/bash.py", line 171, in execute
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: Timeout, PID: 353667
[2021-04-05 07:20:13,105] {taskinstance.py:1433} INFO - Marking task as UP_FOR_RETRY. dag_id=baxa_lead_importer, task_id=main, execution_date=20210405T071000, start_date=20210405T072002, end_date=20210405T072013
[2021-04-05 07:20:13,239] {local_task_job.py:118} INFO - Task exited with return code 1
