[2021-04-05 05:19:58,091] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: baxa_lead_importer.main 2021-04-05T05:00:00+00:00 [queued]>
[2021-04-05 05:19:58,137] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: baxa_lead_importer.main 2021-04-05T05:00:00+00:00 [queued]>
[2021-04-05 05:19:58,138] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-04-05 05:19:58,138] {taskinstance.py:1018} INFO - Starting attempt 5 of 6
[2021-04-05 05:19:58,138] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-04-05 05:19:58,158] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): main> on 2021-04-05T05:00:00+00:00
[2021-04-05 05:19:58,160] {standard_task_runner.py:51} INFO - Started process 26737 to run task
[2021-04-05 05:19:58,177] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'baxa_lead_importer', 'main', '2021-04-05T05:00:00+00:00', '--job-id', '296', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/baxa_lead_importer.py', '--cfg-path', '/tmp/tmp8xvzk2db']
[2021-04-05 05:19:58,180] {standard_task_runner.py:76} INFO - Job 296: Subtask main
[2021-04-05 05:19:58,319] {logging_mixin.py:103} INFO - Running <TaskInstance: baxa_lead_importer.main 2021-04-05T05:00:00+00:00 [running]> on host airflowvm
[2021-04-05 05:19:58,497] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=baxa_lead_importer
AIRFLOW_CTX_TASK_ID=main
AIRFLOW_CTX_EXECUTION_DATE=2021-04-05T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-05T05:00:00+00:00
[2021-04-05 05:19:58,497] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-04-05 05:19:58,498] {bash.py:158} INFO - Running command: sleep 20
[2021-04-05 05:19:58,518] {bash.py:169} INFO - Output:
[2021-04-05 05:20:08,498] {timeout.py:36} ERROR - Process timed out, PID: 26737
[2021-04-05 05:20:08,498] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2021-04-05 05:20:08,537] {taskinstance.py:1396} ERROR - Timeout, PID: 26737
Traceback (most recent call last):
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1295, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/operators/bash.py", line 171, in execute
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: Timeout, PID: 26737
[2021-04-05 05:20:08,538] {taskinstance.py:1433} INFO - Marking task as UP_FOR_RETRY. dag_id=baxa_lead_importer, task_id=main, execution_date=20210405T050000, start_date=20210405T051958, end_date=20210405T052008
[2021-04-05 05:20:08,654] {local_task_job.py:118} INFO - Task exited with return code 1
