[2021-04-02 11:50:01,681] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: fec_lead_importer.main 2021-04-02T11:40:00+00:00 [queued]>
[2021-04-02 11:50:01,714] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: fec_lead_importer.main 2021-04-02T11:40:00+00:00 [queued]>
[2021-04-02 11:50:01,715] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-04-02 11:50:01,715] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-04-02 11:50:01,715] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-04-02 11:50:01,741] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): main> on 2021-04-02T11:40:00+00:00
[2021-04-02 11:50:01,749] {standard_task_runner.py:51} INFO - Started process 649069 to run task
[2021-04-02 11:50:01,761] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'fec_lead_importer', 'main', '2021-04-02T11:40:00+00:00', '--job-id', '260', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/airflow_poc.py', '--cfg-path', '/tmp/tmp6icb4_ey']
[2021-04-02 11:50:01,770] {standard_task_runner.py:76} INFO - Job 260: Subtask main
[2021-04-02 11:50:01,911] {logging_mixin.py:103} INFO - Running <TaskInstance: fec_lead_importer.main 2021-04-02T11:40:00+00:00 [running]> on host airflowvm
[2021-04-02 11:50:02,042] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=fec_lead_importer
AIRFLOW_CTX_TASK_ID=main
AIRFLOW_CTX_EXECUTION_DATE=2021-04-02T11:40:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-02T11:40:00+00:00
[2021-04-02 11:50:02,043] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-04-02 11:50:02,043] {bash.py:158} INFO - Running command: $HOME/workspace/cron-jobs/scripts/standard/leads_importer/fec_importer.sh --client 'fec' --upsert 'true'
[2021-04-02 11:50:02,068] {bash.py:169} INFO - Output:
[2021-04-02 11:50:02,072] {bash.py:173} INFO - bash: /home/airflow/workspace/cron-jobs/scripts/standard/leads_importer/fec_importer.sh: No such file or directory
[2021-04-02 11:50:02,074] {bash.py:177} INFO - Command exited with return code 127
[2021-04-02 11:50:02,105] {taskinstance.py:1396} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-04-02 11:50:02,107] {taskinstance.py:1433} INFO - Marking task as FAILED. dag_id=fec_lead_importer, task_id=main, execution_date=20210402T114000, start_date=20210402T115001, end_date=20210402T115002
[2021-04-02 11:50:02,174] {local_task_job.py:118} INFO - Task exited with return code 1
